---
title: "Resume Experiment"
format: html
execute: 
  echo: false
---


```{r}
#| message: false
#| warning: false

library(tidyverse)
library(tidymodels)
library(broom)
library(marginaleffects)
library(easystats)

x <- read_csv("https://raw.githubusercontent.com/PPBDS/bootcamp/refs/heads/master/_internal/data/resume.csv",
        show_col_types = FALSE)
```
<!-- name indicates applicant's first name.

gender indicates gender.

ethnicity indicates ethnicity (i.e., Caucasian-sounding vs. African-American sounding first name).

quality indicatesquality of resume.

call indicates whether the applicant was called back?

city indicates city: Boston or Chicago.

jobs indicates number of jobs listed on resume.

experience indicates number of years of work experience on the resume.

honors: Did the resume mention some honors?

holes: Does the resume have some employment holes?

special: Does the resume mention some special skills? -->


```{r}
 #| cache: true
#| message:false
#| warning: false

logistic_reg() |> 
  fit(as.factor(call) ~ city, data = x) |> 
  tidy(conf.int = TRUE)
```

```{r}
logistic_reg() |> 
    fit(as.factor(call) ~ ethnicity, data = x) |> 
    tidy(conf.int = TRUE)
```


```{r}
logistic_reg() |> 
    fit(as.factor(call) ~ city + ethnicity, data = x) |> 
    tidy(conf.int = TRUE)
```


```{r}
logistic_reg() |> 
    fit(as.factor(call) ~ gender + city + ethnicity + quality + jobs + special, data = x) |> 
    tidy(conf.int = TRUE)
```


```{r}
logistic_reg() |> 
    fit(as.factor(call) ~ gender + city + ethnicity + special, data = x) |> 
    tidy(conf.int = TRUE)
```

This is my data generating mechanism. 

$$
\begin{equation}
\begin{aligned}
\text{logit}(\Pr(\text{call} = 1)) =\; & -2.75 
\; - \; 0.13 \cdot \text{male} 
\; - \; 0.46 \cdot \text{chicago} \\
& + \; 0.45 \cdot \text{caucasian} 
\; + \; 0.82 \cdot \text{special}
\end{aligned}
\end{equation}
$$
